<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <RootNamespace>StructAI</RootNamespace>
    <RazorComponentNamespaceRoot>StructAI</RazorComponentNamespaceRoot>

    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <UseNativeAot>false</UseNativeAot>
  
    <WasmNative>false</WasmNative>
    <RunAOTCompilation>false</RunAOTCompilation>
    <PublishAot>false</PublishAot>
    <UseWebAssemblyRuntime>false</UseWebAssemblyRuntime>
    <UseWebAssembly>true</UseWebAssembly> <!-- THIS FORCES CLASSIC BLAZOR WASM -->  
  </PropertyGroup>

  <ItemGroup>
    <RazorComponentNamespaceMapping Include="Components" Namespace="StructAI.Components" />
    <RazorComponentNamespaceMapping Include="Components\Fields" Namespace="StructAI.Components.Fields" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
